-- USER SQL
CREATE USER PRATICA IDENTIFIED BY PRATICA 
DEFAULT TABLESPACE "USERS";

-- ROLES
GRANT "CONNECT" TO PRATICA WITH ADMIN OPTION;
GRANT "RESOURCE" TO PRATICA WITH ADMIN OPTION;

-- SYSTEM PRIVILEGES
GRANT CREATE ANY SEQUENCE TO PRATICA WITH ADMIN OPTION;
GRANT CREATE ANY SYNONYM TO PRATICA WITH ADMIN OPTION;
GRANT CREATE ANY VIEW TO PRATICA WITH ADMIN OPTION;
GRANT CREATE ANY TABLE TO PRATICA WITH ADMIN OPTION;
grant execute on utl_file to treinamento;